services:
  - type: web
    name: blood-on-the-clocktower
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOTC_HOST_PIN
        sync: false
